use_frameworks!

platform :ios, '9.0'

target 'LKHomeModule_Example' do
  pod 'LKHomeModule', :path => '../'

  target 'LKHomeModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
